### ISSUE TITLE
Update to Rails 4 and Ruby 2

### ISSUE THREAD

**Issue by eshaiju** [tadast/sublime-rails-snippets#20]
This snippets look great 

can we update this to ruby 2 and Rails 4 ?

**Comment by tadast** [comment]
What snippets in particular are outdated? I'm using it with rails 4.2 and ruby 2.2 and everything works smoothly :)

**Comment by jCrip** [comment]
Maybe update the name of the package or the readme to reflect that this works with ruby 2.2 and rails 4.2

**Comment by tadast** [comment]
I will update the description, thanks.
