### ISSUE TITLE
How to get these snippet up and running in Sublime Text  3 ?

### ISSUE THREAD

**Issue by collegeimprovements** [tadast/sublime-rails-snippets#21]
HI,
Can you please update the README file for ST3 ?
I tried to follow the instructions but can't find Settings directory in the given location.
Plus where to find DetectSyntax.sublime-settings file ?
Thanks.

**Comment by tadast** [comment]
Things have changed in ST3, the best way is to use the package manager. This, however, does not remove the existing plugins so you will have two options when autocompleting things most of the time: one from the original rails snippets and one from this repo.

It's been a while since I had to install this on a fresh ST3 install, so please submit a PR with updates to README once you figure out the best way.

**Comment by collegeimprovements** [comment]
Just wondering which is your goto editor currently ?

**Comment by tadast** [comment]
I'm still using ST3 with this package installed via package manager and am really happy with the setup. It's just been a year or so since I set it up so the installation procedure is better written up by someone with fresh knowledge :)

**Comment by collegeimprovements** [comment]
Ok. I will try and send you a PR if possible :)

**Comment by boddhisattva** [comment]
I followed the below steps to set this package up in Sublime Text 3 -

* Install the package via Package Manger
* You'd need to tell Sublime Text to use the `Ruby on Rails` syntax provided by `Ruby on Rails Snippets`. One can find this option by navigating their way via - `View -> Syntax -> Ruby on Rails Snippets -> Ruby on Rails`

If this works for others, I don't mind submitting a PR for the same.

**Comment by tadast** [comment]
@boddhisattva please do.

**Comment by coderguy** [comment]
@boddhisattva this worked for me.

**Comment by boddhisattva** [comment]
Thanks for confirming this @coderguy . @tadast I'll now send a PR sometime soon.

**Comment by boddhisattva** [comment]
@tadast I've sent a [PR](https://github.com/tadast/sublime-rails-snippets/pull/24) with regard to this issue for your kind review. Thanks for your patience.

**Comment by tadast** [comment]
Thanks

**Comment by boddhisattva** [comment]
:+1:
