### ISSUE TITLE
Mac OS Sublime 3 user here. Issues installing the plugin.

### ISSUE THREAD

**Issue by lifeBalance** [tadast/sublime-rails-snippets#25]
Basically after installing the plugin with Package Control, I can't see the **Ruby on Rails Snippets** among the list of syntaxes to choose from.

**Comment by brianlittmann** [comment]
As an ST3 user, I opted to just override the default Rails snippets instead. Download this repo as a zip, copy all of the `*.sublime-snippet` files to: `~/Library/Application\ Support/Sublime\ Text\ 3/Packages/Rails/` (create the `Rails` directory first if need be) and you should be good to go.

**Comment by lifeBalance** [comment]
@brianlittmann Thanks, I did exactly that plus:
* Renamed the downloaded package to RailsCustom.
* Include the default `Rails` package in the **"ignored_packages"** section of my User Preferences.
