### ISSUE TITLE
Readme points to #Backup for install instructions -- Doesn't exist

### ISSUE THREAD

**Issue by ttilberg** [tadast/sublime-rails-snippets#26]
The current installation instructions in the .readme don't make sense.

After installing, the text file pops up saying there is more to do, and to reference this document.

The Readme links to #Backup but there is no header called #Backup and the instructions don't make sense. I don't know what I'm being asked to remove.

I'm using Sublime3 on Windows.

**Comment by tadast** [comment]
I've updated installation instructions in 6ee79ca0a04ff814ed012d02530b6adc28023451, but I have no windows machine to test on so I only included instructions for Mac users. I'd hope Windows would not be too much different. If you figure it out, let me know (in a form of a PR ideally).
