### ISSUE TITLE
Ruby Haml doesn't have access to snippets?

### ISSUE THREAD

**Issue by Jayphen** [tadast/sublime-rails-snippets#9]
I installed via git clone. 

view.settings shows that I'm using the correct syntax, 

`>>> view.settings().get('syntax')
u'Packages/Rails/Ruby Haml.tmLanguage'

though it seems like I'm getting old snippets. For example, the 'partial' snippet ouputs this:

`= render(:partial => "partial_name")`

I can also see that there is a second Ruby Haml tmLanguage being used. If I delete it, it gets installed again au tomatically on the next launch of Sublime Text.

The snippets are available if I'm using the "Ruby on Rails" syntax, but that doesn't properly highlight Haml.

**Comment by tadast** [comment]
Closing this as stale
